package com.dwc.Events;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.scoreboard.DisplaySlot;
import org.bukkit.scoreboard.Objective;
import org.bukkit.scoreboard.Score;
import org.bukkit.scoreboard.Scoreboard;
import org.bukkit.scoreboard.ScoreboardManager;

import net.milkbowl.vault.Vault;
import net.milkbowl.vault.economy.Economy;

import com.dwc.Main;

public class Events implements Listener {

	Plugin plugin = Main.getPlugin(Main.class) ;
     @EventHandler
      public void onJoin(PlayerJoinEvent event) {
    	 Player player = event.getPlayer();
    	 event.setJoinMessage("");
    	 player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
         player.sendMessage("");
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("header")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("lineone")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("linetwo")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("linethree")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("linefour")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("linefive")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("linesix")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("lineseven")));
    	 player.sendMessage(ChatColor.translateAlternateColorCodes('&', plugin.getConfig().getString("footer")));
     }
	 }